### ISSUE TITLE
use PIE with E:hover, element jitter occurs in IE

### ISSUE THREAD

**Issue by gucong3000** [lojjic/PIE#302]
``` CSS
.somenode {
    behavior: url(/PIE.htc);
    border: 1px solid red;
    border-radius: 5px;
    display: block;
    height: 500px;
    width: 500px;
    margin: 0;
}
.somenode:hover {
    margin: 20px;
}
```

I found a bug of IE:
Sometimes node.offsetTop & node.offsetLeft is not the value we want.
setTimeout for 0Ms, we can get right offsetTop & offsetLeft
