### ISSUE TITLE
PIE don't work in IE8

### ISSUE THREAD

**Issue by gongph** [lojjic/PIE#315]
@lojjic  this is my code:

```
ie8-test
| - css
|    - style.css
|    -  PIE.htc
|- index.html
```

style.css
```css
.box {
  width: 200px;
  height: 200px;
  background: orange;
  position: relative;
  z-index: 10;
  border-radius: 10px;
  -webkit-border-radius: 10px;
  -moz-border-radius: 10px;
  behavior: url(PIE.htc);
}
```

index.html

```
<div class="box"> </div>
```
And then,  I view it in IE8, but `border-radius` don't render.
